apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-jenkins-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-jenkins-app
  template:
    metadata:
      labels:
        app: cloud-jenkins-app
    spec:
      containers:
        - name: cloud-jenkins-app
          image: your-dockerhub-username/cloud-jenkins-app:latest
          ports:
            - containerPort: 8080
